//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class ConfigValidatorErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal ConfigValidatorErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Resources.ConfigValidatorErrorMessages", typeof(ConfigValidatorErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CQuer local API URL from appsettings.json is not valid! It should point to localhost or loopback IP address i.e. https://127.0.0.1:4444.
        /// </summary>
        internal static string APINotLocal {
            get {
                return ResourceManager.GetString("APINotLocal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cannot establish connection with database using connection string from appsettings.json.
        /// </summary>
        internal static string DBConnFailed {
            get {
                return ResourceManager.GetString("DBConnFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CQuer Local API URL from appsettings.json is empty!.
        /// </summary>
        internal static string EmptyAPI {
            get {
                return ResourceManager.GetString("EmptyAPI", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Connection string from appsettings.json is empty.
        /// </summary>
        internal static string EmptyConnectionString {
            get {
                return ResourceManager.GetString("EmptyConnectionString", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Default File Store Path from appsettings.json is empty!.
        /// </summary>
        internal static string EmptyFS {
            get {
                return ResourceManager.GetString("EmptyFS", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Missing Read/Write privileges to directory set as FileStore in appsettings.json.
        /// </summary>
        internal static string FSInvalidPrivileges {
            get {
                return ResourceManager.GetString("FSInvalidPrivileges", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FileStore path from appsettings.json points to non-existing directory!.
        /// </summary>
        internal static string FSNotExists {
            get {
                return ResourceManager.GetString("FSNotExists", resourceCulture);
            }
        }
    }
}
