//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Common.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class DataModelValidationErrorMessages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal DataModelValidationErrorMessages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Common.Resources.DataModelValidationErrorMessages", typeof(DataModelValidationErrorMessages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download URL cannot be empty!.
        /// </summary>
        internal static string EmptyDownloadUrl {
            get {
                return ResourceManager.GetString("EmptyDownloadUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download URL cannot be empty!.
        /// </summary>
        internal static string EmptyUrl {
            get {
                return ResourceManager.GetString("EmptyUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Account Type!.
        /// </summary>
        internal static string InvalidAccountType {
            get {
                return ResourceManager.GetString("InvalidAccountType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ticket ID required!.
        /// </summary>
        internal static string MissingTicketId {
            get {
                return ResourceManager.GetString("MissingTicketId", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Download URL cannot be null!.
        /// </summary>
        internal static string NullUrl {
            get {
                return ResourceManager.GetString("NullUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Passwords are not the same!.
        /// </summary>
        internal static string PasswordMismatch {
            get {
                return ResourceManager.GetString("PasswordMismatch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Severity maximum value is 5.
        /// </summary>
        internal static string SeverityGreaterThanMax {
            get {
                return ResourceManager.GetString("SeverityGreaterThanMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Severity minimum value is 1.
        /// </summary>
        internal static string SeverityLessThanMin {
            get {
                return ResourceManager.GetString("SeverityLessThanMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special characters not allowed in description!.
        /// </summary>
        internal static string SpecialCharactersTicketDescription {
            get {
                return ResourceManager.GetString("SpecialCharactersTicketDescription", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Special characters not allowed in URL!.
        /// </summary>
        internal static string SpecialCharactersUrl {
            get {
                return ResourceManager.GetString("SpecialCharactersUrl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Username cannot contain special characters!.
        /// </summary>
        internal static string SpecialCharactersUsername {
            get {
                return ResourceManager.GetString("SpecialCharactersUsername", resourceCulture);
            }
        }
    }
}
